### ISSUE TITLE
[request] Example without usage of a boilerplate kit, css-modules or withStyles

### ISSUE THREAD

**Issue by JaxCavalera** [kriasoft/isomorphic-style-loader#10]
I've been going through the code and tried to source help on the Discord Reactiflux website to see if I could take the example usage provided and make it work with my own server setup :
https://github.com/JaxCavalera/Tagged_Isomorphic/blob/master/src/server.jsx

The most challenging lines to follow are specifically related to : 
```js
const context = { insertCss: (styles) => css.push(styles._getCss()) };
```
I don't really understand the purpose of using that variable and I'm unsure of where the **styles** variable is being defined or how it ends up being an object with functions such as **_getCss()**.

Will **isomorphic-style-loader** work without the use of the withStyles Higher order function or is that a dependency module that needs to manually be imported and used in each of my components.. which would seem to then signify that I need to also use css-modules so that makes 2 dependencies.

I'm not very clear on css-modules and what benefit it brings to the table.

**Comment by JaxCavalera** [comment]
One of my primary concerns is that I would prefer to keep my Display components "dumb".  From the time I've spent going through the other issues and example code and the source it seems that perhaps this module works by making the "dumb" components aware of state via the context object.

this results in components that would have a significant dependency on a specific module which removes the benefits modularity that were made possible by using a React stack.  Maybe I'm misunderstanding how this works and that's not required.. I just can't seem to get my head around implementation where my class names are actual class names and not variables.

**Comment by frenzzy** [comment]
**1.** In contrast to the [style-loader](https://github.com/webpack/style-loader), isomorphic-style-loader allows you to use the same webpack configuration for CSS in server and client bundles.

ISL just adds to required/imported styles this two methods:
- `styles._getCss()` - isomorphic method which returns CSS string, can be run on the client and on the server.
- `styles._insertCss()` - client-side only method, allows inject your CSS into the [DOM](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model).

Example of a simple one-page application:
```css
/* style.css */
.hello {
  color: red;
}
```
```js
/* server.js */
import styles from './styles.css'
import express from 'express'

const server = express()

server.get('*', (req, res) => {
  res.status(200).send(`
    <!doctype html>
    <html>
      <head>
        <meta charset="utf-8">
        <title>One-page app example</title>
        <style>${styles._getCss()}</style>
      </head>
      <body>
        <p class="hello">Hello world!</p>
      </body>
    </html>
  `)
})

server.listen(3000, () =>
  console.log('The server is running at http://localhost:3000/')
)
```

**2.** ISL does not force you to use CSS Modules, you can use any other loaders together with ISL.

It is also useful to look at the [css-loader](https://github.com/webpack/css-loader) documentation to see how to disable the css-modules.

Example of [webpack](https://webpack.github.io/) configuration for styles:
```js
{
  // ...
  module: {
  loaders: [
    {
      test: /\.css$/, // or .scss
      loaders: [
        'isomorphic-style-loader',
        'css-loader',
        'your-preprocessor-loader' // <==
      ]
    }
  ]
}
```

**3.** To understand the benefits of using [CSS Modules](https://github.com/css-modules/css-modules), please read this article:
- [CSS Modules - Welcome to the Future](http://glenmaddern.com/articles/css-modules) by Glen Maddern

**4.** ISL allow you to render "critical CSS" on the server, during server-side rendering (SSR). Read more about this feature:
- [Understanding Critical CSS](https://www.smashingmagazine.com/2015/08/understanding-critical-css/) by Dean Hume
- [Prioritize Critical CSS](https://developers.google.com/speed/pagespeed/service/PrioritizeCriticalCSS) by Google
- [etc.](https://www.google.com/webhp#newwindow=1&q=critical+css)

So for critical CSS server must send to the client only the styles that are needed for visible html-elements. React provides an excellent component model with lifecycle that makes it easy. The only thing you need to do is somehow to collect the styles for rendered components.

You can write your own critical css collector:
```js
/* styleCollector */
import { canUseDOM } from 'fbjs/lib/ExecutionEnvironment';

const css = []

export function collectOrRender(style) {
  if (canUseDOM) {
    return style._insertCss()
  }

  css.push(style._getCss())
}

export function renderStyles() {
  return css.join('')
}
```

```css
/* MyComponent.css */
.hello {
  color: red;
}
```

```js
/* MyComponent.js */
import React, { Component } from 'react'
import { collectOrRender } from './styleCollector'
import style from './MyComponent.css'

class MyComponent extends Component {
  componentWillMount() {
    this.removeStyle = collectOrRender(style)
  }
  componentWillUnmount() {
    this.removeStyle()
  }
  render() {
    return <div className="hello">Hello world!</div>
  }
}

export default MyComponent
```

```js
/* server */
import express from 'express';
import { renderToString } from 'react-dom';
import { renderStyles } from './styleCollector'
import MyComponent from './MyComponent'

const server = express();

server.get('*', (req, res) => {
  const body = renderToString(MyComponent) // collect all styles
  const css = renderStyles() // get collected styles
  res.status(200).send(`
    <!doctype html>
    <html>
      <head>
        <meta charset="utf-8">
        <title>Critical CSS path example</title>
        <style>${css}</style>
      </head>
      <body>
        <div id="root">${body}</div>
        <script src="/client.js"></script>
      </body>
    </html>
  `)
})

server.listen(3000, () =>
  console.log('The server is running at http://localhost:3000/')
)
```

```js
/* client.js */
import React from 'react'
import { render } from 'react-dom'
import MyComponent from './MyComponent'

render(
  <MyComponent />,
  document.getElementById('root')
)
```

Or just use ISL [withStyles](https://github.com/kriasoft/isomorphic-style-loader#react-component-example) helper.

**Comment by koistya** [comment]
@JaxCavalera the `styles` object is coming from the loader itself, for example:

```js
import s from './MyComponent.css'; // <-- styles object
```

It should have two "magic" methods on it `._getCss()` and `._insertCss()`. If your app is not isomorphic (regular SPA), then you don't need to use the React's context feature but can have the following `withStyles` helper component:

```js

import React, { Component, PropTypes } from 'react';

function withStyles(ComposedComponent, styles) {
  return class Styles extends Component {
    componentWillMount() {
      this.removeCss = styles._insertCss();
    }

    componentWillUnmount() {
      setTimeout(this.removeCss, 0);
    }

    render() {
      return <ComposedComponent {...this.props} />;
    }
  };
}

export default withStyles;
```

And use it the same way with your stateless are stateful React components, for example:

```js
import React from 'react';
import s from './MyComponent.css';

function MyComponent({ name }) {
  return <div className="some-class">Hello, {name}!</div>
}

export default withStyles(MyComponent, s);
```

**Comment by JaxCavalera** [comment]
Hi guys thank you so very much for all this additional information I will be putting all this code to the test tomorrow morning first thing and will report the results.

Silly question probably but I'm just wondering what's the "$" symbol in the JSX code for?  I've never had to use that when inserting a variable or imported component into a Parent Component.

**Comment by koistya** [comment]
@JaxCavalera check out [template strings](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/template_strings) on MDN.

**Comment by JaxCavalera** [comment]
Just a quick update on the progress so far :

I now am understanding a lot better how this particular loader is intended to work.  I'm just trying to work out how to collect my styles without polluting my clean "Dumb" components with functional code and dependencies on external plugins/loaders.. otherwise it would defeat the entire purpose of keeping smart/dumb components and lose all those benefits.

The above solutions provided would not achieve this task so that's why I'm currently at that point now.

Since I define my Index.HTML code inside a separate file, I'm using the String.replace() method to achieve the same result as is achieved using template strings.  Template strings look pretty nice though and I'm sure there will be times where they become the most suitable approach to a task.

So from what I understand, if I am importing a CSS file using
```js
import './home.css';
```
That home.css file once ran through the ISL would have those 2 helper functions attached to it.. not that this helps me really since there's no way of dealing with the problem of using those functions if I want to keep my Display component Dumb.

I keep coming back to the prospect of importing the CSS for a dumb component inside the Smart View Parent but... that would provide very little reason to continue splitting the code up and as mentioned would not result in environment agnostic components that are easy to reuse.

**Comment by JaxCavalera** [comment]
Ok so I put in a lot of contemplating and thought and I believe that in the end if I move the **Importing** of CSS files from the Display to the View component it should still be fine.  Dan Abramov (who first put me onto smart/dumb components in one of his posts) states that CSS belongs in the Dumb components.

I realise now that it doesn't matter what react based project you are using, you will still wind up with all components being split into a "smart" and "dumb" part but will always be paired together.  To use that dumb Display component outside of this context it will only require adding the import css line provided that no css-modules or variable based classNames are used keeping everything clean still.

This was probably immediately obvious to others but required me to come to terms with potential problems that I might encounter if I were to break a previously declared structuring rule for working with "smart" and "dumb" components.

That being said and done I'll be coding up this first test run now to see how it goes and will report back with the results when it's completed.

**Comment by JaxCavalera** [comment]
Ok some great news and a little bit of a glitch as well :

**The good news** : I got the server-side css working without using css-modules or string templates.

String templates wouldn't work in my situation due to the HTML template file being defined as a string literal in a separate module to not crowd the server.jsx code.  Used the replace function to get around this problem so wasn't an issue

**The glitch** :
When the static HTML version is served up it has the <styles></styles> tags with server-side parsed CSS/SASS etc in there as expected.

Once the client-side bundle.js downloads and takes over, there is no visible flicker since styling doesn't change.. however in the code I noticed that it doesn't replace the original <styles></styles> tags .. it appends another pair below it with a duplicate version of the same CSS code.

I'm not fully sure why this is happening.

Relevant project files are :

View Component :
<https://github.com/JaxCavalera/Tagged_Isomorphic/blob/master/src/client/home/views/home-body-view.jsx>

Style Collector (slightly modified) :
<https://github.com/JaxCavalera/Tagged_Isomorphic/blob/master/src/styleCollector.jsx>

Server :
<https://github.com/JaxCavalera/Tagged_Isomorphic/blob/master/src/server.jsx>

**Comment by JaxCavalera** [comment]
Glitch is now fixed by adding lines 5 and 6 to the following file, which is only loaded client-side :
<https://github.com/JaxCavalera/Tagged_Isomorphic/blob/master/src/client-render.jsx>

Thank you all very much for helping get this working, really appreciate it and hopefully this information will further encourage the usage of this module since it's simply awesome :)

**Comment by Sawtaytoes** [comment]
How would I handle this with multiple stylesheets pulled into the same module? It seems to only insert the first one and ignore the others.

**Comment by thebigredgeek** [comment]
https://github.com/thebigredgeek/isomorph-style-loader < There is an active fork here with the latest round of changes, including `hoist-non-react-statics` integration on the decorator

**Comment by Sawtaytoes** [comment]
Thanks for that link! I don't understand what you mean when you say 
>`hoist-non-react-statics` integration on the decorator

How's the fork different from this one?
