### ISSUE TITLE
Integrate with react-select

### ISSUE THREAD

**Issue by psyanite** [kriasoft/isomorphic-style-loader#102]
I'm using react-starter-kit and I would very much love to use react-select from https://github.com/JedWatson/react-select in my project. 

I did a bit of Googling but could not find a proper solution on how to load the CSS styles. 
I've tried to do this with my `Filters` component using the example on the `react-select` main page.
```
import selectStyles from 'react-select/dist/react-select.css';
...
export default withStyles(selectStyles)(withStyles(s)(Filters));
```
But I believe, because of how isomorphic-style-loader functions, it cannot apply the CSS styles??? 
![capture](https://user-images.githubusercontent.com/24215698/29235890-c6eb59e0-7f46-11e7-8009-17e5676b9318.PNG)

If anyone has any suggestions for me, I would be greatly appreciative.

**Comment by frenzzy** [comment]
Probably you need to configure [`css-loader`](https://github.com/webpack-contrib/css-loader) to not use [css modules](https://github.com/webpack-contrib/css-loader#modules) for that file (it is already [configured](https://github.com/kriasoft/react-starter-kit/blob/9aafdb4499932ebbf83e47af2c9a33e1e709d4a8/tools/webpack.config.js#L118-L127) in master branch or [RSK](https://reactstarter.com/)).

Hint: you may use single [hoc](https://facebook.github.io/react/docs/higher-order-components.html) to apply multiple style sheets.
```js
export default withStyles(s, selectStyles, orAnyOtherStyles)(Filters);
```

**Comment by psyanite** [comment]
Hey @frenzzy thanks for all the help. I think I finally got it working now. I'm going to close this issue til I run into trouble again. Thanks ;)
