### ISSUE TITLE
babel-node syntax error

### ISSUE THREAD

**Issue by BinahLinden** [kriasoft/isomorphic-style-loader#11]
When running in development babel-cli (babel-node) is throwing syntax error on CSS imports when I run my server.js. Any suggestion on how to solve this? 

`products.scss: Unexpected token (1:0)
> 1 | .products {
    | ^
  2 |   padding-top: 24px;
  3 |   padding-bottom: 24px;`

I've seen the suggestion to wrap css in conditional requires based on ENV, but that doesn't seem to fit in with server side rendering concept that this plugin is solving.

**Comment by koistya** [comment]
This loader accepts the output from `css-loader`, which might be preceded by `sass-loader` / `postcss-loader` etc. that is capable of handling `@import` statements in CSS/SCSS code.

See [/tools/webpack.config.js#L76-L82](https://github.com/kriasoft/react-starter-kit/blob/d496698e9be478774e004d6135d27b8fa522385d/tools/webpack.config.js#L76-L82), [/tools/webpack.config.js#L99-L105](https://github.com/kriasoft/react-starter-kit/blob/d496698e9be478774e004d6135d27b8fa522385d/tools/webpack.config.js#L99-L105) in React Starter Kit

**Comment by BinahLinden** [comment]
Thank you for quick response. I should have been more specific in my question. The import that babel is not liking is in my React module, as taken from example on README, I have changed my CSS import to

`import withStyles from 'isomorphic-style-loader/lib/withStyles';
import s from './Product.scss';`

Then in my npm script I run 
` "dev": "NODE_PATH=$NODE_PATH:./server babel-node server/server.js"`

the babel-cli, babel-node, is throwing syntax error when I run.

**Comment by koistya** [comment]
@BinahLinden it's seems to me that you're trying to run the code, which has not been yet transpiled by Webpack. Node.js interpreter expects JavaScript code in imported (required) files. E.g. `.root{color:red;}` should be transpiled to something like this by Webpack `module.exports = '.root{color:red}';` (converts CSS string to JavaScript code).

**Comment by BinahLinden** [comment]
Yes you are correct, I am running in development mode with files that get processed by webpackDevMiddleware, which I had hoped would solve that issue. I am looking at `extract-text-webpack-plugin` maybe that will help. Thank you for your help.

**Comment by koistya** [comment]
@BinahLinden I see.. I guess, the problem in `style-loader` config in your server-side bundle. You may want to check out [isomorphic-style-loader](https://github.com/kriasoft/react-starter-kit), which has the same config for both server-side and client-side bundles, you can use it to extract critical CSS for server-side rendering purposes, also it allows to keep in DOM only CSS that is actually used by React components rendered on the page.

**Comment by koistya** [comment]
`extract-text-webpack-plugin` is an alternative solution to this Webpack loader, it extracts all the CSS from your React app. `isomorphic-style-loader` on the other hand allows to extract only critical path CSS, better for performance and also it's easier to configure.

**Comment by anaibol** [comment]
Hi @koistya I am having this same issue and I've been dealing all day with webpack configs. Is there any simple webpack configuration that shows simple "isomophic style loading"? React Starter Kit config are pretty complicated to be separated from all the boilerplate. I am coming from "react-redux-universal-hot-example" wich haves  pretty different configs and dependencies.

As far as I understood I have to compile all the server. Isn't there any other way?

Thanks!

**Comment by SudoPlz** [comment]
+1
