### ISSUE TITLE
published react components

### ISSUE THREAD

**Issue by veeramarni** [kriasoft/isomorphic-style-loader#113]
Does not seem to work with published react components that will be reused in the application. 

For example, here is the published react component. 

Presentation Component
---
```
import withStyles from 'isomorphic-style-loader/lib/withStyles';
import s from 'package/lib/file.css';

const component = () => (<div ref="container" className='test'/>)

export default withStyles(s)(XtermComponent);
```

And after published this package to `npm`. I would like to use the package in the application which HOC uses `withStyles` but I get following error

![image](https://user-images.githubusercontent.com/3382355/31868087-0183469a-b768-11e7-8f43-3e98dafed2b6.png)

**Comment by frenzzy** [comment]
It works with any types of components, you just need to provide `insertCss` function via react context, for example see https://github.com/kriasoft/isomorphic-style-loader/issues/15#issuecomment-202035615
