### ISSUE TITLE
won't work with scoped node_modules

### ISSUE THREAD

**Issue by veeramarni** [kriasoft/isomorphic-style-loader#114]
This library was hitting the same problem as well. 

https://github.com/sass/node-sass/issues/1596

For example, if I import like below, it won't work.

```
import styles from '@materialui/drawer/drawer.css'
```

**Comment by frenzzy** [comment]
`isomorphic-style-loader` does not handle `import`s in css, it's [`css-loader`](https://github.com/webpack-contrib/css-loader) work.
