### ISSUE TITLE
How to restyle child component?

### ISSUE THREAD

**Issue by godzsa** [kriasoft/isomorphic-style-loader#129]
I have a component called A and it contains B in the definition of A I want to overwrite some properties of B. How should I do that?

For example:
```
A.scss
.black {
   background-color: black;

   .overwriteThis {
      background-color: red;
   }
}

A.js
<div className={s.black}>
   <B />
</div>

==============
B.scss
.root{
  color: white;
}

.overwriteThis {
 background-color: blue;
}

B.js
<div className={s.root}>
   <p className={s.overwriteThis}>
</div>
```

So as you can see I want to overwrite the background color of p in the child component (B) from the parent component (A). 

How to achieve this?

**Comment by frenzzy** [comment]
Use props to change component behavior, don't try to override styles from different modules it is horrible to support. For example: `<MyComponent theme="light" />`. It is much easier to live without cross-dependencies in css. CSS Modules are awesome!

**Comment by godzsa** [comment]
@frenzzy Can you show me an example?

**Comment by frenzzy** [comment]
**src/components/Button/Button.css**
```css
.light {
  background: white;
  color: black;
}
.dark {
  background: black;
  color: white;
}
```

**src/components/Button/Button.js**
```js
import s from './Button.css'
import cx from 'classnames'
const Button = (props) => (
  <button className={s[props.theme]}>{props.children}</button>
)
Button.defaultProps = { theme: 'light' }
export default Button
```

Use the component everywhere:
```js
<Button>Example</Button>
```
When you need a special behavior use props to configure your component:
```js
<Button theme="dark">Special Case</Button>
```
Or if behavor is too custom, use separate component:
```js
<CustomButton>Very Custom Case</CustomButton>
```
