### ISSUE TITLE
How do i override styles from third party libraries?

### ISSUE THREAD

**Issue by damiangreen** [kriasoft/isomorphic-style-loader#134]
e.g. `dashboardWidgetContainer` is a class that I own, `react-grid-item` and `react-resizable-handle` i don't 

I'd like to be able to do something like this:
```
.dashboardWidgetContainer .react-grid-item > .react-resizable-handle::after {
  content: '';
  position: absolute;
  right: 3px;
  bottom: 3px;
  width: 5px;
  height: 5px;
  border-right: 2px solid rgba(255, 255, 255, 0.6);
  border-bottom: 2px solid rgba(255, 255, 255, 0.6);
}
```

**Comment by frenzzy** [comment]
Looks like you are asking in a wrong place. This loader does nothing with your styles, it just allows it ti use them on the server.

**Comment by damiangreen** [comment]
well it kinda does do stuff to your styles, it mangles class names

**Comment by frenzzy** [comment]
Nope, this loader does not modify class names.
You are probably talking about `css-loader` and its **CSS Modules** related option: https://github.com/webpack-contrib/css-loader#modules

**Comment by damiangreen** [comment]
My apologies. thanks for the link
