### ISSUE TITLE
Use stable public API for context

### ISSUE THREAD

**Issue by tstirrat15** [kriasoft/isomorphic-style-loader#150]
[This line](https://github.com/kriasoft/isomorphic-style-loader/blob/master/src/withStyles.js#L18) references context as the second prop of the constructor, which [isn't a part of the public API](https://reactjs.org/docs/react-component.html#constructor). According to the docs for context, the proper way to reference it is [as a property of `this`](https://reactjs.org/docs/context.html#classcontexttype).

I think this may be related to why I'm seeing an error:
```
react_1               | TypeError: Cannot read property 'apply' of undefined
react_1               |     at new WithStyles (/usr/src/app/build/webpack:/node_modules/isomorphic-style-loader/withStyles.js:28:1)
```

which is this compiled code:
```javascript
      function WithStyles(props, context) {
        var _this;

        _this = _React$PureComponent.call(this, props, context) || this;
        _this.removeCss = context.insertCss.apply(context, styles); // right here
        return _this;
      }
```

**Comment by tstirrat15** [comment]
Hmm... Adding some debugging code to the compiled code shows that the context object is completely empty. How would that ever be the case?

Shouldn't it be showing the default `{ insertCss: null }` even if I managed to misconfigure the provider somehow?

**Comment by tstirrat15** [comment]
I'm wrong about the cause of this issue. Any ideas on what could be causing this?

**Comment by tstirrat15** [comment]
Never mind, just found it. I didn't see that you need to be on React 16.6 for `Component.contextType` to be picked up, and my project is currently on 16.4.2. We'll get that upgraded and then try again.

In the meantime, though, is the PR still correct/helpful? Otherwise feel free to close.

**Comment by DongShi** [comment]
Hey @frenzzy  and @tstirrat15 , I see you guys revert this PR #151 
Is there any plan on how to handle the private API (context as a 2nd parameter) in future?

I think the new Context API works well in other lifecycle methods but not in constructor...

see a related discussion here:
https://github.com/facebook/react/issues/12397#issuecomment-505283823
