### ISSUE TITLE
How to import root style without prefix?

### ISSUE THREAD

**Issue by digz6666** [kriasoft/isomorphic-style-loader#157]
I'm trying to import root style into my client side index.js file. how can I do that?

Following index.less file is not loaded or added to my dom.
```js
...
import './index.less';
...

const insertCss = (...styles) => {
  const removeCss = styles.map(style => style._insertCss());
  return () => removeCss.forEach(dispose => dispose());
};

ReactDOM.render(
  <StyleContext.Provider value={{ insertCss }}>
    <Router>{renderRoutes(Routes)}</Router>
  </StyleContext.Provider>,
  document.getElementById('root')
);
```

Example project is here: https://github.com/digz6666/webpack-loader-test/tree/ssr-2

**Comment by piglovesyou** [comment]
If you only would like to load a single `.less` file you might not need `isomorphic-style-loader` but you just can write `<link rel="stylesheet" href="index.css">` in your `<head>` to load your compiled `.less` .

If you still would like to use `isomorphic-style-loader` you can try this in both client-side and server-side entry points:

```js
import s from './index.less';
//...
insertCss(s);
```

In order not to put prefix, pleaser refer to [css-loader options](https://github.com/webpack-contrib/css-loader#options).

**Comment by digz6666** [comment]
@piglovesyou Thank you. importCss(s) resolved my problem.

**Comment by piglovesyou** [comment]
Nice to hear that.
