### ISSUE TITLE
Unable to use isomorphic-style-loader without CSS modules

### ISSUE THREAD

**Issue by Sawtaytoes** [kriasoft/isomorphic-style-loader#17]
I'm having trouble understanding how this style loader is supposed to work based on the documentation. I don't use CSS modules myself so `<div className={s.root}>` won't work for me.

Looking down the documentation, I see something like this:
```
  const css = []; // CSS for all rendered React components
  const context = { insertCss: (styles) => css.push(styles._getCss()) };
```

To me, this seems like what I want, but I don't know where CSS is getting any styles. I tried this myself and CSS is always `[]`.

My goal is not have Webpack generating pages on load. I have backend.js for the server and bundle.js for the client already working, and I don't wanna use ExtractTextPlugin anymore as it's not choosy about what CSS is loaded; it's a one-time thing.

I'm looking for a method of taking a bunch of site styles (based on what was imported already) and add them to the `<head><style>${css}</style></head>` server-side on load, then change that back to using style-loader client-side. I thought it'd be nice if I could modify style-loader to do this for me, but it directly writes to the DOM and doesn't have any way of writing to a global string that I can push onto the page myself. isomorphic-style-loader seems to be capable of doing this, but it's unclear how I'm supposed to tell it which styles were loaded so I can generate a style tag.

**Comment by frenzzy** [comment]
maybe this answers will be helpful to you: #10

**Comment by Sawtaytoes** [comment]
You are correct! That did help. It's complex and annoying to do in each module, but yes, it works exactly like that on client and server. I really appreciate your answer and will be closing this ticket. It's definitely the solution to what I was looking for; albeit, really messy code-wise.
