### ISSUE TITLE
Can not only use css-loader5.x with isomorphic-style-loader^5.1.0?

### ISSUE THREAD

**Issue by zejunking** [kriasoft/isomorphic-style-loader#187]
When used with css-loader^5.0.0, there is an error that style css cannot be extracted?
The return of _getCss() is ` [object Module]  ` ?
Can only use css-loader3.x 0.28.x with isomorphic-style-loader^5.1.0

**Comment by dbousamra** [comment]
I also had this.

**Comment by unbugx** [comment]
You can find solution here https://stackoverflow.com/questions/63458657/isomorphic-style-loader-doesnt-work-as-it-supposed-to/63983963#63983963 You have to disable esModule flag

**Comment by dazlious** [comment]
I think this is the correct answer. Thanks @unbugx

**Comment by dazlious** [comment]
I think this is the correct answer. Thanks @unbugx
