### ISSUE TITLE
import css does not return the classes

### ISSUE THREAD

**Issue by kbruneel** [kriasoft/isomorphic-style-loader#188]
Hi,

When I do: `import s1 from "./button.css";`

And then try: `s1.button` 

This returns `undefined`.

When I `console.log(s1)` I get:
```
{_getContent: ƒ, _getCss: ƒ, _insertCss: ƒ}
_getContent: ƒ ()
_getCss: ƒ ()
_insertCss: ƒ (options)
__proto__: Object
```

button.css contains:
```
.button {
  ...
}
```

In my webpack config I have:
```
  {
      test: /\.(css|scss)$/,
      use: [
          'isomorphic-style-loader',
          {
              loader: "css-loader",
              options: {
                  importLoaders: 1
              }
          },
          'postcss-loader'
      ]
  }
```

I'm really out of ideas of what I'm doing wrong. Thanks for your help!
Karel

**Comment by unbugx** [comment]
Hi @kbruneel whats version of css-loader do you use?

**Comment by the-vvv** [comment]
Seeing the same issue. Tried with css-loader 3.6.0 and 5.0.1.

**Comment by the-vvv** [comment]
Fixed by adding "modules: true" to css-loader options.

**Comment by dazlious** [comment]
Closing, as this issues has a solution.
