### ISSUE TITLE
React 18 peerDependencies support

### ISSUE THREAD

**Issue by chestnutchen** [kriasoft/isomorphic-style-loader#205]
Is it better to be a greater than or equal（>= 16.8.0）？ #193

**Comment by horrylala** [comment]
using `--force` still works
> npm  install isomorphic-style-loader@latest --force

but i got type checking warnings:
> Warning: Failed prop type: Invalid prop `__$$withStylesRef` supplied to `R`, expected one of type [function].
The solution is modified withStyles propTypes or remove whole withStyles typeChecking.

I don't know whether there is a better way to handle css in SSR.

**Comment by paulmcconico** [comment]
Any idea when #206 will be deployed and available in NPM?

**Comment by zjye-idealhub** [comment]
Looking forward on this release too

**Comment by dazlious** [comment]
https://github.com/kriasoft/isomorphic-style-loader/tree/v5.4.0
