### ISSUE TITLE
New version 5.3.2 does not have the react 18 in peer dependency

### ISSUE THREAD

**Issue by shreyasvimal** [kriasoft/isomorphic-style-loader#213]
When I install the version 5.3.2, it throws error for react version `^18.0.0`. The new version does not have the latest PR and is not supporting the react 18.

**Comment by adrien-febvay** [comment]
Duplicate of https://github.com/kriasoft/isomorphic-style-loader/issues/205

**Comment by dazlious** [comment]
https://github.com/kriasoft/isomorphic-style-loader/tree/v5.4.0
