### ISSUE TITLE
ignore some styles

### ISSUE THREAD

**Issue by Kepro** [kriasoft/isomorphic-style-loader#3]
Hi,

i using also react-bootstrap, and i want to override some styles of bootstrap... but i can't (i can but not for all elements)

is there some flag for ignore? or how i can tell to don't rename this style?

**Comment by dsernst** [comment]
Ignore what? Why does this module not let you override some bootstrap styles?

**Comment by Kepro** [comment]
omg, sorry that does this
````
          'css-loader?' + (DEBUG ? 'sourceMap&' : 'minimize&') +
          'modules&localIdentName=[local]',
````
