### ISSUE TITLE
How to reference a class from another stylesheet without renaming it?

### ISSUE THREAD

**Issue by nuclearspike** [kriasoft/isomorphic-style-loader#30]
I want to do something like:

`.my_app_header_class { .some-component-i-dont-manage { color: #ccc } }`

But I would like to indicate for the .some-component-i-dont-manage to not get renamed since it needs to match the class in the npm package.

Adding className to the component I'm using is one way, however this doesn't work when that component has nested elements it creates that I need to reference.

What is the proper way to do this?

**Comment by frenzzy** [comment]
isomorphic-style-loader does not rename classes. In your case, probably it does [css-loader with enabled css modules](https://github.com/webpack/css-loader#css-modules). You can switch it off with `:global(...)` or `:global` for selectors and/or rules.
```css
.rename :global(.do-not-rename) {}

#your .mega.selector {
  :global {
    #some-component {}
    .you-dont-manage {}
  }
}
```

**Comment by nuclearspike** [comment]
Thank you so much! I tried looking around but didn't find this.
