### ISSUE TITLE
Q: why not a decorator?

### ISSUE THREAD

**Issue by Kepro** [kriasoft/isomorphic-style-loader#31]
Hi, just simple question, why is not as function and not as decorator?

**Comment by koistya** [comment]
@Kepro it seems like class-level decorators are not supported, but you're right it needs to be compatible with decorator syntax.

**Comment by Kepro** [comment]
ok, so we need to wait for ES7 heh :)

**Comment by koistya** [comment]
I think that the latest version, v1.0.0 must be compatible with decorator syntax.
