### ISSUE TITLE
How to include external styles without prefixing?

### ISSUE THREAD

**Issue by Ehesp** [kriasoft/isomorphic-style-loader#36]
Lets say I want to use [Flexbox Grid](https://github.com/kristoferjoseph/flexboxgrid) in my application. I have a root `App` component, which is the main component everything is rendered inside.

The `flexboxgrid` css contains classes which I'd like to use throughout other components. However, they get prefixed with the `App` component name and hash. There's a couple of workarounds, but none seem good/clean enough.

### 1 - By directly including it in the document

This would mean doing it the vanilla way in the document `<head>`. However we can't bundle/control it with webpack and it's an additional HTTP call.

### 2 - Use require & a CSS only loader with ExtractTextPlugin

Now in our `App` component we can use `require('flexboxgrid');`. However this assumes that all `.css` files are external global modules.

<hr />

Work around 2 is the cleanest, however I just feel there should be a way to include styles with the isomorphic style loader without prefixing. Normalize.css will work fine, since it doesn't have any CSS classes, but importing a global CSS file with classes is a faff.

**Comment by koistya** [comment]
@Ehesp can you please try something like this:

#### `App.js`

```js
import React from 'react';
import cx from 'classnames';
import withStyles from 'isomorphic-style-loader/lib/withStyles';
import s1 from '!!isomorphic-style!css?modules=false!./flexbox.grid';
import s2 from './App.scss';

function App({ children }) {
  return (
    <div className={cx(s1.grid, s2.root)}>
      <h1>My App</h1>
      <main>{children}</main>
    </div>
  );
}

export default withStyles(s1, s2)(App);
```

The goal is to override `modules=true` -> `modules=false` flag in the [`css-loader`](https://github.com/webpack/css-loader).

**Comment by Ehesp** [comment]
So sort of working.

This line doesn't work:

```
export default withStyles(s1, s2)(App);
```
This throws an error: TypeError: Cannot call a class as a function

Changing it to:

```
export default withStyles(App, s1, s2);
```

This works, however just the first styles only which is the problem I've just raised in the other ticket https://github.com/kriasoft/isomorphic-style-loader/issues/37.

**Comment by Ehesp** [comment]
Just realised there's a new version out. After upgrading, multiple styles still don't seem to work.

In your example, `s1` gets injected, `s2` does not.

**Comment by digz6666** [comment]
> ```js
> !!isomorphic-style!css?modules=false!./flexboxgrid.css
> ```

Can I set modules=false on @import in less files?
