### ISSUE TITLE
What's the recommended approach for updating styles when client-side route updates

### ISSUE THREAD

**Issue by grgur** [kriasoft/isomorphic-style-loader#41]
Ok so let's say that our isomorphic app changes route and the client side router changed the view based on JavaScript. Is there an official approach to retrieving the CSS that was not already inserted in `<head>`?

In other words:
1. User navigates to the web site. 
2. Server side renderer returns HTML + CSS with help from isomorphic-style-loader
3. Server also returns the JS bundle used to render views on the client side (a-la SPA style)
4. User wants to go to the Account page. Account link is clicked.
5. Client side router changes view to Account.
6. The Account page is rendered on the client side and shown

--
ok, here's my question
7. How should I retrieve the CSS needed for the Account page to show?

--
One approach could be to use the `ExtractTextPlugin`, but that doesn't seem to work (because ExtractTextPlugin loader doesn't know how to call `_getCss()`.

Any ideas?

Thanks a bunch

**Comment by frenzzy** [comment]
With [React.js](https://facebook.github.io/react/) you can use the convenient decorator function `withStyles(styles)(MyReactComponent)`, take a look at the [docs](https://github.com/kriasoft/isomorphic-style-loader#react-component-example) and [source code](https://github.com/kriasoft/isomorphic-style-loader/blob/master/src/withStyles.js).

In your own framework, you must call the `_insertCss` and `_getCss` functions manually, example:
```js
// frontend
import s from './PageStyles.css'
const removeCss = s._insertCss() // mount
removeCss()                      // unmount

// backend
import s from './PageStyles.css'
const response = s._getCss()     // css string
```

**Comment by grgur** [comment]
@frenzzy thanks a bunch for a quick answer.

Ok, so the way i see it - `insertCss` function basically gets CSS from the CSS module object (`import s from './PageStyles.css'`). That's great when it's on the server side, but how exactly do I fetch that CSS object if I'm already on the front-end? Obviously loader's css objects are kept on the server side, no?
Does my question make sense?

**Comment by frenzzy** [comment]
You should use isomorphic-style-loader for both client-side and server-side bundles. Frontend uses `_insertCss` to mount styles to the DOM, backend uses `_getCss` to prepare html string which will be responded to the client-side. You can find a working example in [React Starter Kit](https://www.reactstarterkit.com/):
- [tools/webpack.config.js](https://github.com/kriasoft/react-starter-kit/blob/master/tools/webpack.config.js#L79)
- [src/client.js](https://github.com/kriasoft/react-starter-kit/blob/master/src/client.js#L19)
- [src/server.js](https://github.com/kriasoft/react-starter-kit/blob/master/src/server.js#L98)

**Comment by grgur** [comment]
Ok so basically the thing i was interested in is how *the rest* of the css (besides critical path) is transferred to the client. Looks like it's bundled in JS.

Thanks

**Comment by koistya** [comment]
@grgur yep, it's bundled into JavaScript bundle (or chunks) and it's usually a good idea to load that bundle asynchronously, for example, in the `<head>` section of your HTML page:

```html
<script async src="/bundle.js"></script>
```

**Comment by grgur** [comment]
Yes, exactly how i had it set up. 

Thank you for open sourcing this. It's top notch!
