### ISSUE TITLE
How to write proper handler in insertCss on client side for multiple arguments in withStyles? 

### ISSUE THREAD

**Issue by Everettss** [kriasoft/isomorphic-style-loader#45]
Suggested in #37 by @frenzzy handling for multiple arguments in `withStyles` function
`withStyles(s1, s2)(Component)`
on the **client side** was:

```javascript
const onInsertCssHandler = (...styles) => {
    styles.forEach(style => style._insertCss());
};

ReactDOM.render(
    <WithStylesContext onInsertCss={onInsertCssHandler}>
        // irrelevant 
    </WithStylesContext>,
    document.getElementById('root')
);
```

**WithStylesContext** - just for documentation:
```javascript
import { Component, PropTypes, Children } from 'react';

class WithStylesContext extends Component {
    static propTypes = {
        children: PropTypes.element.isRequired,
        onInsertCss: PropTypes.func.isRequired,
    };

    static childContextTypes = {
        insertCss: PropTypes.func.isRequired,
    };

    getChildContext() {
        return { insertCss: this.props.onInsertCss };
    }

    render() {
        return Children.only(this.props.children);
    }
}

export default WithStylesContext;
```

This solution indeed append multiple styles properly, but has **problem with removing them** when [they are no longer referenced by UI components](https://github.com/kriasoft/isomorphic-style-loader/blob/master/src/insertCss.js#L25).

I think the issue is related with not returning function in `onInsertCssHandler`. For reference: [original handler in react-starter-kit](https://github.com/kriasoft/react-starter-kit/blob/master/src/client.js#L19).

How to write this handler and still have removing not used styles functionality?

**Comment by frenzzy** [comment]
It removes in componentWillUnmount inside withStyles decorator, see [src/withStyles.js#L25-L31](https://github.com/kriasoft/isomorphic-style-loader/blob/6ff8064187a95a28c0ed5f779d841ead02a3d317/src/withStyles.js#L25-L31)

**Comment by Everettss** [comment]
Fully working `insertCss handler`:

```javascript
const onInsertCssHandler = (...styles) => {
    const removeCss = styles.map(style => style._insertCss());
    return () => {
        removeCss.forEach(f => f());
    }
};
```
