### ISSUE TITLE
How to use pseudo classes from imported style sheets?

### ISSUE THREAD

**Issue by shishirarora3** [kriasoft/isomorphic-style-loader#48]
Is there a way to use pseudo class bases styles like a:after {}

I am missing some documentation here. Please guide.

**Comment by frenzzy** [comment]
The same way when you don't use this loader.

**Comment by shishirarora3** [comment]
Import s from ''../abc.css";
render: <t className={classNames (s.b,s.a)}/>

.b.a:after {
Content:'*';
}


This does not seem to work. I will check further but in generated classes I dont find psedo class elments/ classes.



W

**Comment by shishirarora3** [comment]
Import s from ''../abc.css";
render: <div className={classNames (s.a,s.b)}>
<i></i>
</div>

.b.a i:after {
Content:'*';
}

This does not seem to work. I will check further but in generated classes I dont find psedo class elments/ classes.

**Comment by shishirarora3** [comment]
Sorry markup is removing everyone I post
``
<div className={classNames (s.a,s.b)}>
<i></i>
</div>``
