### ISSUE TITLE
Where is `context` set?

### ISSUE THREAD

**Issue by dsernst** [kriasoft/isomorphic-style-loader#5]
I'm trying to add this to server-side render a particular component with its style.

I've installed this package and prepended it to the list of loaders for `.scss`:

```diff
  module: {
    loaders: [
      JS_LOADER,
      ...config.module.loaders,
      {
        test: /\.scss$/,
-        loaders: ['css-loader', 'postcss-loader'],
+        loaders: ['isomorphic-style-loader', 'css-loader', 'postcss-loader'],
      },
    ],
  },
```

I've added all the code described in the readme for stateless react components:

```js
import React, { PropTypes } from 'react'
import style from './About.scss'

function About(props, context) {
  console.log('context:', context)
  context.insertCss(style)
  return (
    <div className="About">
      ...
    </div>
  )
}

About.contextTypes = { insertCss: PropTypes.func.isRequired }

export default About
```

But when I try to build this on the server (using `npm start` from [`react-static-boilerplate`](https://github.com/koistya/react-static-boilerplate)) these errors are thrown:

```
Warning: Failed Context Types: Required context `insertCss` was not specified in `About`. Check the render method of `_default`.
context: { insertCss: undefined }
TypeError: context.insertCss is not a function
    at new About (/Users/dsernst/Documents/project/build/app.node.js:1401:13)
```

Any idea why `context.insertCss` is `undefined`? Is there a step I'm missing? Was I supposed to invoke `getChildContext` somewhere up the tree?

**Comment by koistya** [comment]
Yep, you need to add `getChildContext() { }` into your top-level React component (e.g. `<Layout />`) which sets a custom `insertCss` function, which might be as simple as `(styles) => styles._insertCss()` for client-side code and `(styles) => { css.push(styles._getCss(); }` for server-side code.

Here is a helper component, which does `context.insertCss(style)` for you:

```js
import React, { Component, PropTypes } from 'react';

function addStyles(BaseComponent, ...styles) {
  return class StyledComponent extends Component {
    static contextTypes = {
      insertCss: PropTypes.func.isRequired,
    };

    componentWillMount() {
      this.removeCss = this.context.insertCss.apply(undefined, styles);
    }

    componentWillUnmount() {
      this.removeCss();
    }

    render() {
      return <BaseComponent {...this.props} />;
    }
  };
}

export default addStyles;
```

Usage sample:

```js
import React, { PropTypes } from 'react';
import style from './About.scss';

function About(props, context) {
  return (
    <div className="About">
      ...
    </div>
  );
}

About.contextTypes = { insertCss: PropTypes.func.isRequired };

export default addStyles(About, style);
```

**Comment by dsernst** [comment]
Ok, it seems a bit more complicated for [`react-static-boilerplate`](https://github.com/koistya/react-static-boilerplate), because there's no `css` to push into for the context.

I've gotten it mostly working, by updating:

- app.js
- components/Html/Html.js
- components/Layout/Layout.js
- components/About/About.js (e.g. `MyComponent.js`, for testing)
- package.json
- tools/render.js
- tools/webpack.config.js

But one aspect that still doesn't work right now is HMR, nor am I setting a different context on the server vs client. Since this question is now answered. I'll close this Issue and reopen as a PR over in that project.

Thanks for your help.

**Comment by mqliutie** [comment]
@koistya 
I'm sorry I think I did not do it correctly. There is my code
```
class Todos extends React.Component {

    constructor ({staticContext}) {
        super();
        // if (AppUtil.isClient()) {
        //     style._insertCss();
        // } else {
        //     staticContext.insertCss(style);
        // }
    }

    getChildContext () {
        return {
            insertCss: (styles) => styles._insertCss()
        }
    }

    async componentDidMount () {
        const { todo = {}, dispatch } = this.props;
        const { todoList } = todo;
        if (todoList.length <= 0) {
            dispatch(getTodoList());
        }
    }

    render () {
        const { todo } = this.props;
        const { todoList } = todo;
        return <ul className={style.test}>{todoList.map(todo => <li key={todo.id}>{todo.title}</li>)}</ul>;
    }
}

export default withStyles(style)(Todos);
```

The error was shown `Uncaught TypeError: Cannot read property 'apply' of undefined`
```
this.removeCss = (_context = this.context).insertCss.apply(_context, styles);
```

`isomorphic-fetch` version is  `2.2.1`

**Comment by mqliutie** [comment]
>Note:

>The legacy context API will be removed in a future major version. Use the new context API >introduced with version 16.3. The legacy API will continue working for all 16.x releases.

My react version is `16.4.2` the api may have changed. I should use new api
