### ISSUE TITLE
Use just client side?

### ISSUE THREAD

**Issue by rossthedevigner** [kriasoft/isomorphic-style-loader#59]
I just came across this project today and I'm not quite sure if this is something that can be used JUST client side (static-only site) to grab the critical path css?

**Comment by alex-shamshurin** [comment]
If server's css would be different from client's you will get react warning. So it must be identical.

**Comment by koistya** [comment]
@rossthedevigner yes, this loader can be used ONLY on the client-side, yet you will get the benefit of having only minimum set of CSS mounted into the DOM at any given point in time while user browsers the site. E.g. if <Layout><Product /></Layout> is rendered, only styles for these two components are going to be rendered into the dom, when user goes to <Login /> screen, CSS that no longer in use removed from the dom and CSS for the Login component (plus child components if any) is mounted into the DOM. This optimizes the memory usage in the browser, performance, unlocks code-splitting pattern.

**Comment by alex-shamshurin** [comment]
@koistya You mean I use it wrong in webpack server config?

**Comment by koistya** [comment]
@alex-shamshurin most likely you're building an isomorphic app, in which case you must you this loader in both server-side and client-side Webpack configurations.

**Comment by alex-shamshurin** [comment]
So do I, but you pointed in last answer that the loader is only for a client side...

> this loader can be used ONLY on the client-side

**Comment by koistya** [comment]
@alex-shamshurin some web apps don't need server-side code at all, e.g. when you're building an app for hosting in Firebase, in that case, there is no any server-side Webpack config.
