### ISSUE TITLE
Overriding library CSS classes 

### ISSUE THREAD

**Issue by brandon-arnold** [kriasoft/isomorphic-style-loader#79]
Hi there,

Is there a way to process a CSS file with withStyles and leave some of the classes' names as-is? 

```css
.myClass.container {
   /* some CSS */
}
```

```js
render() {
    return (
       <div className={s.myClass}>
           <Container></Container>
       </div>
    );
}
```

Assuming the above ```<Container``` component will render with ```class="container"```, for example if it were a Bootstrap container, then I would like some way for my CSS above to be able to select it. But when the CSS gets loaded by Webpack, it gets an ID, viz.:

```css
.myClass_3eF.container_1l6 {
  /* my CSS */
}
```

Which causes ```container_1I6``` for example never to reference the required class. I would like some way to ensure ```myClass``` does get its ID, and ```container``` retains its name. Is this possible?

**Comment by frenzzy** [comment]
`isomorphic-style-loader` does not modify your css files, you probably have to look at [`css-loader`](https://github.com/webpack-contrib/css-loader) configuration.
```css
.myClass:global(.container) {}
/* => .myClass_3eF.container {} */
```

**Comment by brandon-arnold** [comment]
Awesome. Thanks for the comment, @frenzzy--you're right, the ```css-loader``` is doing it. I found you have to decorate those classnames with ```:global```, as in ```:global(.container) { /* My CSS */ }```.
