### ISSUE TITLE
Support React 15.5.0

### ISSUE THREAD

**Issue by plemarquand** [kriasoft/isomorphic-style-loader#89]
React 15.5.0 issues a warning that `PropTypes` and `React.createClass` should be pulled from separate dependencies instead of being imported from React itself (`React.createClass` is only used in the tests). This warning is in anticipation of React 16 which will remove them all together.

To fix, remove imports of PropTypes from `react` and import it instead from the `prop-types` package. Also import `createClass` from the `create-react-class` package instead of `react`.

**Comment by 4refr0nt** [comment]
Please, increment version number for upgrading.
