### ISSUE TITLE
bootstrap withstyle loader

### ISSUE THREAD

**Issue by afonsoSoares** [kriasoft/isomorphic-style-loader#95]
Hello everyone,
when i  do 
`import s from "./style.css"
className={s.nav-item} `

I get the error item not exist.
How to get class with "-" in the name.
Thanks.

**Comment by frenzzy** [comment]
`s['nav-item']`

**Comment by afonsoSoares** [comment]
Thank you and you know how to pass multiple class
's['nav-item']s['nav-tab']'

**Comment by frenzzy** [comment]
```js
className={s['nav-item'] + ' ' + s['nav-tab']}
```
or
```js
className={`${s['nav-item']} ${s['nav-tab']}`}
```
or
```js
import cx from 'classnames'; // https://github.com/JedWatson/classnames
className={cx(s['nav-item'], s['nav-tab'])}
```

**Comment by afonsoSoares** [comment]
ok, thank you.


2017-06-06 17:00 GMT+01:00 Vladimir Kutepov <notifications@github.com>:
