### ISSUE TITLE
How to use `withStyles` with a named export?

### ISSUE THREAD

**Issue by lzacharkow** [kriasoft/isomorphic-style-loader#96]
Hi there! I'm new to isomorphic-style-loader and I'm running into an issue with using `withStyles` with named exports (not `default` exports).

My goal is to be able to import any of the components in my file with the relevant styles.

Here's the basic file structure I have in my `Styleguide.js` file. I have a default component and I also have a few named exports:
```js
import s from './Styleguide.scss';

function Styleguide() {
    ...
}

export function Links() {
    ...
}

export function Buttons() {
    ...
}

export default withStyles(s)(Styleguide);
```

Do you know how can I export `Links` and `Buttons` with styles? I've tried writing it a variety of ways, but I always run into a syntax error. What's the right way to do this?

I know that one obvious solution would be to move my named exports into their own files with default exports in each, but I'd love to be able to do it this way instead.

Thanks for your help!

**Comment by lzacharkow** [comment]
Figured it out!
```js
import s from './Styleguide.scss';

function Styleguide() {
    ...
}

function LinksComponent() {
    ...
}

function ButtonsComponent() {
    ...
}

const Links = withStyles(s)(LinksComponent);
const Buttons = withStyles(s)(ButtonsComponent);

export {
    Links,
    Buttons
};

export default withStyles(s)(Styleguide);
```

**Comment by x5engine** [comment]
thanks
